# Generated by Django 6.0.2 on 2026-09-07 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_tag_product_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="description",
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
